apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: db
  template:
    metadata:
      labels:
        app.kubernetes.io/service: db
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: GDSCTF
          image: mysql
          name: db
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
