apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: app-
namespace: devops-tools
metadata:
  name: codingame-ressources
commonLabels:
  app: codingame

resources:
- ./base
- ./mysql
